import { afterEach, expect, it, vi } from 'vitest'

afterEach(() => vi.unstubAllGlobals())

it('does not save the temporary onboarding layout as the Advanced workspace', async () => {
  window.localStorage.clear()
  vi.resetModules()
  const grow = vi.fn()
  vi.stubGlobal('hermesDesktop', { guestOnboardingEnabled: true, chatOnboarding: { grow } })
  const { DEFAULT_TREE, BASIC_TREE, registerLayoutPresets } = await import('@/app/contrib/layout-presets')
  const tree = await import('@/components/pane-shell/tree/store')
  const mode = await import('@/store/interface-mode')
  const panes = await import('@/store/panes')
  const guide = await import('./assembly')
  registerLayoutPresets()
  tree.declareDefaultTree(DEFAULT_TREE, BASIC_TREE)
  panes.setPaneWidthOverride('chat-sidebar', 310)
  const sizes = structuredClone(panes.$paneStates.get())
  const before = structuredClone(tree.$layoutTree.get())
  guide.startChatOnboardingSolo()
  expect(tree.$activePresetId.get()).toBe('chat-solo')
  guide.assembleChatOnboarding('sidebar-left', BASIC_TREE, 'simple')
  expect(mode.$interfaceMode.get()).toBe('simple')
  expect(grow).toHaveBeenCalledOnce()
  mode.setInterfaceMode('advanced')
  expect(tree.$layoutTree.get()).toEqual(before)
  expect(panes.$paneStates.get()).toEqual(sizes)
  expect(tree.$activePresetId.get()).toBe('default')
})
